-- phpMyAdmin SQL Dump
-- version 5.1.1
-- https://www.phpmyadmin.net/
--
-- Máy chủ: 127.0.0.1
-- Thời gian đã tạo: Th10 08, 2021 lúc 09:12 PM
-- Phiên bản máy phục vụ: 10.4.21-MariaDB
-- Phiên bản PHP: 8.0.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Cơ sở dữ liệu: `btl_cnweb`
--

-- --------------------------------------------------------

--
-- Cấu trúc bảng cho bảng `db_content`
--

CREATE TABLE `db_content` (
  `id` int(11) NOT NULL,
  `cid` int(11) NOT NULL,
  `name` varchar(250) COLLATE utf8mb4_unicode_ci NOT NULL,
  `vn_title` varchar(250) COLLATE utf8mb4_unicode_ci NOT NULL,
  `e_title` varchar(250) COLLATE utf8mb4_unicode_ci NOT NULL,
  `price` int(50) NOT NULL,
  `market_price` int(50) NOT NULL,
  `save_money` int(50) NOT NULL,
  `img` varchar(250) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `img_big` varchar(250) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `info` varchar(10000) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `details_product` varchar(1000) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `use_product` varchar(500) COLLATE utf8mb4_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Đang đổ dữ liệu cho bảng `db_content`
--

INSERT INTO `db_content` (`id`, `cid`, `name`, `vn_title`, `e_title`, `price`, `market_price`, `save_money`, `img`, `img_big`, `info`, `details_product`, `use_product`) VALUES
(1, 1, 'B-O-M', 'Kem Chống Nắng B.O.M SPF50+/PA++++ 50ml', 'Green UV Sun Off', 425000, 510000, 81000, 'https://media.hasaki.vn/catalog/product/k/e/kem-chong-nang-b-o-m-spf50-pa-50ml_img_300x300_b798dd_fit_center.jpg', 'https://media.hasaki.vn/wysiwyg/UYEN/kem-chong-nang-bom-spf50-pa_5_.jpg', 'Chắc hẳn ai trong chúng ta cũng đã hơn một lần cùng tìm hiểu và nghe qua những ảnh hưởng xấu, tác hại lên làn da từ các tia cực tím (UV) tồn tại trong ánh nắng mặt trời, dễ dàng khiến da bị đen sạm, lão hóa, thậm chí dẫn đến viêm da hay ung thư da. Cho nên chọn cho mình một loại kem chống nắng thích hợp và hiệu quả để bảo vệ làn da là rất cần thiết. Kem chống nắng SPF 50+/PA++++ đến từ thương hiệu B.O.M với chỉ số chống nắng mạnh mẽ, thẩm thấu nhanh và không gây bóng nhờn, sẽ là trợ thủ đắc lực che chắn cho làn da bạn trước tác hại từ ánh nắng mặt trời và giúp da bạn luôn căng mọng, rạng rỡ. ', 'Chiết xuất hoa hồng Chống ôxy hóa mạnh mẽ, chống viêm lỗ chân lông, làm giảm vết thâm, mụn, mang đến làn da mềm mại, mịn màng', '- Lấy một lượng kem chống nắng vừa đủ thoa đều lên da. \r\n\r\n- Sử dụng sản phẩm trước khi ra ngoài trời 20 phút.'),
(2, 1, 'TENAMYD', 'Kem Chống Nắng Trà Xanh TENAMYD SPF42/PA++ 70ml', 'Green Tea Protective Sunscreen SPF42/PA++', 429000, 51000, 81000, 'https://media.hasaki.vn/catalog/product/k/e/kem-chong-nang-tra-xanh-tenamyd-spf42-pa-70ml_img_300x300_b798dd_fit_center.jpg', 'https://media.hasaki.vn/wysiwyg/quynhtrang/Trang/kem-chong-nang-tra-xanh-tenamyd-spf42-pa-70ml.jpg', 'Sản phẩm Kem Chống Nắng Trà Xanh TENAMYD Green Tea Protective Sunscreen SPF42/PA++ với chiết xuất từ trà xanh, lô hội cùng các hợp chất thảo dược chính là bí quyết vừa giúp duy trì được lớp bảo vệ và dưỡng da hiệu quả, vừa giúp dưỡng ẩm, làm mát và hỗ trơ tăng độ sáng mịn cho da.', '-Chiết xuất trà xanh:\nGiảm tình trạng sưng tấy, kích ứng da, ngăn ngừa mụn, chống oxi hóa, chống lão hóa da\n-Chiết xuất lô hội:\nLàm giảm mụn, làm dịu da, giảm sưng tấy, dưỡng ẩm, làm se lỗ chân lông và ngăn ngừa các dấu hiệu lão hóa.', ''),
(3, 1, 'Cathy Doll', 'Kem Chống Nắng Cathy Doll Sáng Da SPF50/PA+++ 138ml', 'L-Glutathione Magic Cream', 155000, 245000, 90000, 'https://media.hasaki.vn/catalog/product/k/e/kem-chong-nang-cathy-doll-sang-da-spf50-pa-138ml-2_img_300x300_b798dd_fit_center.jpg', 'https://media.hasaki.vn/wysiwyg/Dai/kem-chong-nang-cathy-doll-sang-da-spf50-pa-138mlj.jpg', 'Chắc hẳn ai trong chúng ta cũng đã hơn một lần cùng tìm hiểu và nghe qua những ảnh hưởng xấu, tác hại lên làn da từ các tia cực tím (UV) tồn tại trong ánh nắng mặt trời, dễ dàng khiến da bị đen sạm, lão hóa, thậm chí dẫn đến viêm da hay ung thư da. Cho nên chọn cho mình một loại kem chống nắng thích hợp và hiệu quả để bảo vệ làn da là rất cần thiết. Kem Chống Nắng Trắng Da Cathy Doll SPS50/PA+++ từ thương hiệu Cathy Doll với chỉ số chống nắng mạnh mẽ, thẩm thấu nhanh và không gây bóng nhờn, không thấm nước đồng thời dưỡng trắng và mang đến hiệu ứng trắng da tức thời sẽ là trợ thủ đắc lực che chắn cho làn da bạn trước tác hại từ ánh nắng mặt trời và giúp da bạn luôn căng mọng, rạng rỡ.', 'Thành phần chínhNội dung đang được cập nhật', 'Bóp một lượng sản phẩm vừa đủ và thoa lên những vùng da muốn chống nắng. Nên thoa sản phẩm tầm 15 ~ 20\' trước khi ra ngoài để sản phẩm thẩm thấu hoàn toàn vào da và đạt hiệu quả cao.'),
(4, 1, 'CHIFURE', 'Kem Chống Nắng Chifure Dạng Sữa SPF50+ PA++++ 30ml', 'Sunscreen Milk UV SPF50+ PA++++', 277000, 380000, 31000, 'https://media.hasaki.vn/catalog/product/g/o/google-shopping-kem-chong-nang-chifure-dang-sua-spf50-pa-30ml_img_300x300_b798dd_fit_center.jpg', 'https://media.hasaki.vn/wysiwyg/HaNguyen/kem-chong-nang-chifure-dang-sua-spf50-pa-30ml-2.jpg', 'Kem Chống Nắng CHIFURE Sunscreen Milk UV SPF50+ PA++++ là sản phẩm chống nắng dành cho da mặt và toàn thân đến từ thương hiệu CHIFURE (Nhật Bản). Công thức chống nắng dạng sữa lỏng nhẹ cung cấp khả năng bảo vệ da lâu dài trước tia UV gây hại, đồng thời tạo cảm giác thoải mái dễ chịu trong suốt thời gian sử dụng, hoàn toàn không để lại vệt trắng trên da.\r\n\r\nKem Chống Nắng Dạng Sữa CHIFURE Sunscreen Milk UV SPF50+ PA++++ 30ml hiện đã có mặt tại Hasaki.', 'Cyclopentasiloxane 35.40%, neopentyl glycol dicaprate 6.00%, dimethicone 4.00%, ethylhexyl methoxycinnamate 7.99%, titanium dioxide 6.05%, zinc oxide 5.03%, diethylamino hydroxybenzoyl hexyl benzoate 2.00%, butylene glycol 4.00%, stearyl glycyrrhetinate 0.05%, trehalose 0.03%, sodium hyaluoronate 0.01%, alcohol 3.00%, polymethylsilsesquioxane 1.00%, dimethicone/vinyl dimethicone crossspolymer 0.10%, PEG-10 dimethicone 1.78%, PEG-9 polydimethylsiloxyethyl dimethicone 1.70%, hydrated silica 1.12%, hydrogen dimethicone 0.50%, aluminum hydroxide 0.27%, methylparaben 0.30%, disodium EDTA 0.05%, sodium citrate 0.05%, BHT 0.01%, tocopherol, water.', '-Do sản phẩm có kết cấu dạng 2 lớp nên cần lắc đều chai trước khi sử dụng.\r\n\r\n-Lấy lượng nhỏ kem chống nắng và chia thành nhiều lần thoa, thoa đều lên da mặt và toàn thân, những nơi tiếp xúc với ánh nắng mặt trời.\r\n\r\n-Nếu da còn ẩm, hãy lau khô trước khi thoa kem chống nắng.\r\n\r\n-Nên thoa lại sau mỗi 2-3 tiếng tiếp xúc với ánh nắng.\r\n\r\n-Nếu bạn dùng tay hoặc khăn để lau mồ hôi, hãy thoa lại kem chống nắng để đạt hiệu quả tối ưu nhất.\r\n\r\n-Làm sạch kem chống nắng với sản phẩm tẩy trang chuyên dụng '),
(5, 1, ' Neogen', 'Kem Chống Nắng Neogen Dermalogy Chống Ánh Sáng Xanh 50ml', 'Day-Light Protection Sunscreen SPF 50 PA+++', 348000, 50000, 152000, 'https://media.hasaki.vn/catalog/product/f/a/facebook-dynamic-kem-chong-nang-neogen-dermalogy-chong-anh-sang-xanh-50ml_img_300x300_b798dd_fit_center.jpg', 'https://media.hasaki.vn/wysiwyg/HaNguyen/kem-chong-nang-neogen-dermalogy-chong-anh-sang-xanh-50ml-1.jpg', 'Kem Chống Nắng Neogen Dermalogy Chống Ánh Sáng Xanh là dòng sản phẩm chống nắng dành cho da mặt đến từ thương hiệu Neogen, có khả năng chống nắng chuyên sâu, giúp chống lại tác hại của tia UVA/UVB trong mọi hoạt động hằng ngày, đồng thời chống ánh sáng xanh phát ra từ các thiết bị điện tử, bảo vệ da tối đa, ngăn ngừa xuất hiện các dấu hiệu lão hóa và tình trạng da khô ráp, xỉn màu - thâm sạm. Bên cạnh đó, sản phẩm còn cung cấp độ ẩm dịu nhẹ cho da luôn ẩm mượt suốt cả ngày dài, đồng thời làm dịu các tổn thương và trả lại làn da khỏe mạnh, tràn đầy sức sống.\r\n\r\nHiện Kem Chống Nắng Neogen Dermalogy Day-Light Protection Sunscreen SPF 50 PA+++ 50ml đã có mặt tại Hasaki.', 'Water, Ethylhexyl Methoxycinnamate, Glycerin, Butylene Glycol, Bis-Ethylhexyloxyphenol Methoxyphenyl Triazine, Zinc Oxide, C12-15 Alkyl Benzoate, Hexanediol, Isoamyl P-Methoxycinnamate, Dicaprylyl Carbonate, Titanium Dioxide, Cetearyl Alcohol, Xanthan Gum, Polysorbate 20, Sodium Hyaluronate, Glyceryl Stearate, Peg-100 Stearate, Acrylates/C10-30 Alkyl Acrylate Crosspolymer, Portulaca Oleracea Extract, Lavandula Angustifolia (Lavender) Oil, Phyllanthus Emblica Fruit Extract, Rubus Idaeus(Raspberry) Fruit Extract, Vaccinium Angustifolium (Blueberry) Fruit Extract, Euterpe Oleracea Fruit Extract, Ammonium Acryloyldimethyltaurate/Vp Copolymer, Carbomer, Lippia Citriodora Leaf Extract, Rosa Damascena Flower Extract, Tocopheryl Acetate, Angelica Archangelica Root Extract, Beta-Glucan, Hibiscus Sabdariffa Flower Extract, Artemisia Absinthium Extract, Arnica Montana Flower Extract, Polyhydroxystearic Acid, Alumina, Gentiana Lutea Root Extract, Achillea Millefolium Extract, Litsea Cubeba Fruit O', '-Sử dụng như bước cuối cùng của quy trình chăm sóc da ban ngày, trước các bước trang điểm.\r\n\r\n-Thoa lượng kem vừa đủ cho da mặt và cổ, kết hợp thao tác thoa - vỗ nhẹ nhàng để kem thẩm thấu hết vào da.'),
(6, 1, ' L\'OREAL', 'Kem Chống Nắng L\'Oréal Kiềm Dầu Thoáng Mịn Da 30ml', 'UV Perfect Matte & Fresh SPF 50+/PA++++', 118000, 148000, 30000, 'https://media.hasaki.vn/catalog/product/k/e/kem-chong-nang-kiem-dau-l-oreal-spf-50-pa-30ml-1_1_img_300x300_b798dd_fit_center.jpg', 'https://media.hasaki.vn/wysiwyg/Dai/kem-trang-diem-chong-nang-spf50-pa-30ml-p.jpg', 'Nắng hè sẽ không còn là nỗi lo với kem chống nắng L\'Oréal UV Perfect SPF50/PA+++ 30ml: che phủ làn da bạn, bảo vệ da khỏi ánh nắng hè gay gắt giúp da sáng hồng rạng rỡ, đều màu tự nhiên. Ưu điểm chống nắng có chỉ số chống nắng cao đến SPF50, lại được kết hợp khả năng chống oxi hóa và thay thế kem lót, là sản phẩm trang điểm kết hợp chống nắng nhanh và tiện dụng cho mọi phụ nữ.\r\n\r\nL\'OREAL là thương hiệu mỹ phẩm nổi tiếng đến từ Pháp và có mạng lưới bán hàng rộng khắp toàn cầu. Đây là thương hiệu có đầy đủ mọi sản phẩm làm đẹp “từ đầu đến chân” dành cho phụ nữ, gồm mỹ phẩm chăm sóc tóc, mỹ phẩm trang điểm, chăm sóc da,… Các sản phẩm L\'OREAL không những phổ biến trên thị trường mà còn được phân phối tại các salon chăm sóc sắc đẹp chuyên nghiệp.', 'Nội dung đang được cập nhật', 'Sử dụng vào ban ngày, trước khi ra nắng 30 phút, sau các bước dưỡng da thông thường, và trước các bước trang điểm tiếp theo (nếu có). Dùng một lượng kem vừa đủ (chỉ khoảng 1 hạt bắp) và chia đều trên năm điểm của khuôn mặt (trán, mũi, cằm, hai bên má). Sau đó, thoa đều nhẹ nhàng khắp mặt. Nên dùng thêm cho vùng da ở cổ. Tránh tiếp xúc trực tiếp với mắt. \r\n\r\nBảo quản:\r\n\r\nTránh ánh nắng trực tiếp.\r\n\r\nĐể nơi khô ráo, thoáng mát.\r\n\r\nĐậy nắp kín sau khi sử dụng.\r\n\r\nDung tích: 30ml\r\n\r\nThương hiệu: L\'O'),
(7, 1, 'CARENEL', 'Kem Chống Nắng CARE:NEL Nâng Tone Da SPF50 PA++++ 50ml', 'No Sebum Perfect UV Shield', 265000, 310000, 45000, 'https://media.hasaki.vn/catalog/product/g/o/google-shopping-kem-chong-nang-care-nel-nang-tone-da-spf50-pa-50ml-1_img_300x300_b798dd_fit_center.jpg', 'https://media.hasaki.vn/wysiwyg/minhchau/kem-chong-nang-care-nel-nang-tone-da-spf50-pa-50ml-1.jpg', 'Làn da của chúng ta tiếp xúc với ánh nắng mỗi ngày, cho dù đó là thời điểm nóng nhất của mùa hè hay trong những ngày lạnh giá của mùa đông. Dù nhiều chuyên gia đưa ra khuyến cáo về việc sử dụng kem chống nắng ngay cả khi trời âm u, nhiều người vẫn không thực sự nhận thức được tầm quan trọng của bước chăm sóc da này. Việc thoa kem chống nắng giúp da không chỉ đơn thuần tránh được sự bỏng rát, hơn thế nữa, kem chống nắng giúp phân tán hoặc hấp thu tia UV, ngăn chặn chúng tiếp xúc với ánh nắng từ sâu bên trong da, giúp cấu trúc da không bị phá hủy âm thầm từ bên trong. Kem Chống Nắng Nâng Tone Da SPF50 PA++++ No Sebum Perfect UV Shield – một sản phẩm đa năng vừa chống nắng vừa nâng tone da từ hãng mỹ phẩm Hàn Quốc Carenel sẽ cho các cô gái thêm một lựa chọn nữa khi vừa muốn chống nắng, vừa muốn có một làn da sáng ngời.', 'Nội dung đang được cập nhật', '- Lấy 1 lượng vừa đủ thoa đều lên da trước khi ra nắng 20 phút để kem phát huy tác dụng.\r\n\r\nNhững lưu ý khi sử dụng:\r\n\r\n- Trong quá trình sử dụng nếu thấy da có các biểu hiện khác thường như: xuất hiện các vết đỏ,  ngứa, hay bị kích ứng thì phải ngưng sử dụng ngay và hỏi ý kiến tư vấn từ chuyên gia da liễu.\r\n\r\n- Không thoa lên các vùng da bị viêm, bị chàm bội nhiễm hay các vùng da bị thương.'),
(8, 1, 'SOME BY MI', 'Kem Chống Nắng SOME BY MI SPF50+/PA++++ 50ml', 'Truecica Mineral 100 Calming Suncream', 260000, 335000, 75000, 'https://media.hasaki.vn/catalog/product/g/o/google-shopping-kem-chong-nang-some-by-mi-spf50-pa-50ml_img_300x300_b798dd_fit_center.jpg', 'https://media.hasaki.vn/wysiwyg/minhchau/kem-chong-nang-some-by-mi-spf50-pa-50ml-1.jpg', 'Kem Chống Nắng SOME BY MI Truecica Mineral Calming Suncream SPF50+/PA++++ 50ml đến từ thương hiệu SOME BY MI được thiết kế dành riêng cho làn da nhạy cảm và dễ bị mụn, mang đến công dụng 3 trong 1: chống nắng, dưỡng sáng da, giảm nếp nhăn.\r\n\r\n', 'Water, Cetyl Ethylhexanoate, Butylene Glycol, Glycerin, Dipropylene Glycol, Zinc Oxide, Silica, 1,2-Hexanediol, Niacinamide, Polyglyceryl-3 Methylglucose Distearate, Melaleuca Alternifolia (Tea Tree) Leaf Water, Titanium Dioxide, Sodium Polyacryloyldimethyl Taurate, Cetearyl Olivate, Sorbitan Olivate, Stearic Acid, Citrus Aurantium Dulcis (Orange) Peel Oil, Lauroyl Lysine, Disodium EDTA, Acrylates/C10-30 Alkyl Acrylate Crosspolymer, Melaleuca Alternifolia (Tea Tree) Leaf Oil, Lavandula Angustifolia (Lavender) Oil, Adenosine, Centella Asiatica Extract, Artemisia Vulgaris Extract, Caprylyl Glycol, Madecassoside, Asiaticoside, Asiatic Acid, Madecassic Acid', '-Sử dụng vào buổi sáng hoặc trước khi ra nắng, sau bước làm sạch da.\r\n-Cho lượng kem chống nắng bằng khoảng 1/4 muỗng cafe và chấm đều thành nhiều điểm lên da mặt.\r\nKết hợp thao tác vỗ nhẹ và tán đều để kem chống nắng thẩm thấu hết vào da.\r\n-Đừng quên thoa phần da cổ, gáy, sau tai... để bảo vệ da toàn diện.\r\n-Thoa lại sau mỗi 2-3 tiếng di chuyển liên tục dưới nắng.\r\n-Tẩy trang sạch sau khi về nhà với sản phẩm tẩy trang chuyên dụng.'),
(9, 1, 'Neutrogena', 'Kem Chống Nắng Ultra Sheer SPF 50 88ml', 'Ultra Sheer Dry Touch SPF 50 88ml', 279000, 400000, 121000, 'https://media.hasaki.vn/catalog/product/g/o/google-shopping-kem-chong-nang-neutrogena-ultra-sheer-dry-touch-spf-55-2_img_300x300_b798dd_fit_center.jpg', 'https://media.hasaki.vn/wysiwyg/minhchau/kem-chong-nang-neutrogena-ultra-sheer-dry-touch-spf-55-2.jpg', 'Kem Chống Nắng Neutrogena Ultra Sheer SPF50 88ml là sản phẩm chống nắng đến từ thương hiệu mỹ phẩm Neutrogena của Mỹ, với công nghệ Dry-touch mới giúp da khô thoáng, kết hợp cùng công nghệ Helioplex, có khả năng chống nắng phổ rộng, tăng độ bền vững dưới tác động của tia UV giúp bảo vệ da lâu dài hơn, bảo vệ bạn khỏi tác hại của ánh nắng mặt trời một cách triệt để. Hiện sản phẩm Kem Chống Nắng Neutrogena Ultra Sheer SPF50 88ml đã có mặt tại Hasaki.', 'Avobenzone 3%, Homosalate (10%), Octisalate (5%), Octocrylene (2.8%), Oxybenzone 6%, Water, Butyloctyl Salicylate, Styrene Acrylates Copolymer, Silica, Diethylhexyl 2 6 Naphthalate, VP/Hexadecene Copolymer, Dimethicone, Ethylhexl Glycerin, Caprylyl Methicone, Phenoxyethanol, Ethylhexyl Stearate, BHT, Glyceryl Stearate, PEG 100 Stearate, Trideceth 6, Behenyl Alcohol, Trimethylsiloxysilicate, Sodium Polyacrylate, Xanthan Gum, Disodium EDTA, Methylparaben, Iodopropynyl Butylcarbamate, Propylparaben, Ethylparaben, Fragrance.', '-Bôi kem trước khi ra nắng 15 phút.\r\n\r\n-Sau khi bơi lội, chảy mồ hôi nhiều, hoặc khi ở dưới mặt trời khá lâu nên dùng thêm 1 lớp kem để bảo vệ da tốt nhất.'),
(10, 1, 'VACOSI', 'Kem Chống Nắng Và Lót Trang Điểm VACOSI SPF50 PA+++', 'Natural Studio BB Base Sun Protect', 259000, 280000, 21000, 'https://media.hasaki.vn/catalog/product/k/e/kem-chong-nang-va-lot-trang-diem-vacosi-spf50-pa_img_300x300_b798dd_fit_center.jpg', 'https://media.hasaki.vn/wysiwyg/Camtien/kem-chong-nang-va-lot-trang-diem-vacosi-spf50-pa-1.jpg', 'Water, Titanium Dioxide, Cyclopentasiloxane, Glycerin, Ethylhexyl Salicylate, Ethylhexyl Methoxycinnamate, Dimethicone, Zinc Oxide, Diisostearyl Malate, Niacinamide, Cetyl PEG/PPG-10/1 Dimethicone, Hexyl Laurate, PEG-10 Dimethicone, Ozokerite, Sodium Chloride, Cyclohexasiloxane, Dimethicone/Vinyl Dimethicone Crosspolymer, Stearic Acid, Alumina, Sorbitan Sesquioleate, Magnesium Aluminum Silicate, Isododecane, Caprylyl Glycol, Triethoxycaprylylsilane, Fragrance, Butylphenyl Methylpropional, Benzyl Benzoate, Alpha-Isomethyl Ionone, Citronellol, Geraniol, Coumarin, Linalool, Cinnamyl Alcohol, Benzyl Alcohol, Eugenol, Isoeugenol, Allantoin, Disodium EDTA, Disteardimonium Hectorite, Ethylhexylglycerin, Adenosine, Propylene Carbonate.', '', '-Làm sạch da, cho một lượng nhỏ thoa đều lên mặt, và vùng cổ để bảo vệ làn da. Sau đó vỗ nhẹ cho đến khi kem hấp thu hoàn toàn.\r\n-Sử dụng hàng ngày trước khi ra ngoài nắng từ 15 – 20 phút.\r\n-Bạn cũng có thể trang điểm nhanh vào buổi sáng bằng cách thoa đều kem lên mặt. Sau đó dùng phấn phủ nhẹ nhàng để tạo độ mịn màng, săn chắc cho làn da đẹp tự nhiên, an toàn.'),
(11, 1, 'SEOULROSE', 'Kem Chống Nắng Seoulrose Dưỡng Sáng Da Ban Ngày 45ml', 'Rosa Perfect Whitening S+ Cream SPF35 PA++', 205000, 255000, 50000, 'https://media.hasaki.vn/catalog/product/k/e/kem-chong-nang-seoulrose-duong-sang-da-ban-ngay-spf35-pa-45ml-04_img_300x300_b798dd_fit_center.jpg', 'https://media.hasaki.vn/wysiwyg/ThuyHao/kem-chong-nang-duong-sang-da-ban-ngay-seoulrose-rosa-perfect-whitening-s-cream-spf35-pa-45ml-4.jpg', 'Kem Chống Nắng Dưỡng Sáng Da Ban Ngày SeoulRose Rosa Perfect Whitening S+ Cream SPF35 PA++ 45ml từ thương hiệu SeoulRose của Hàn Quốc là sản phẩm 2 trong 1 với thành phần dưỡng sáng da đồng thời có khả năng chống nắng dịu nhẹ. Việc dưỡng trắng cần chống nắng như một bước cấp thiết, không thể bỏ qua. Với sự kết hợp 2 công dụng trong 1 sản phẩm kem chống nắng giúp da mau chóng sáng khỏe, không bắt nắng trở lại.', 'Thành phần chính\r\n vitamin B1,B2, E, khoáng chất, cám gạo, Niacinamide, Amino acid, Bsasm, Rau má, Tinh chất trà xanh Camellia sinensis leaf extract, cam thảo...', 'Lấy 1 lượng kem vừa đủ lên toàn khuôn mặt ở bước cuối cùng trong quá trình chăm sóc da, vỗ nhẹ để kem thấm qua da. bạn sẽ thấy da sáng lên và mịn màng trông thấy\r\n\r\nThoa kem trước khi ra đường 15 phút để có hiệu quả chống nắng cao'),
(12, 1, 'VICHY', 'Kem Chống Nắng Vichy Cải Thiện Các Dấu Hiệu Lão Hóa 50ml', 'Ideal Soleil Anti-Aging SPF50 UVA + UVB', 378000, 505000, 127000, 'https://media.hasaki.vn/catalog/product/2/0/201600072-0610_img_300x300_b798dd_fit_center.jpg', 'https://media.hasaki.vn/wysiwyg/HaNguyen/kem-chong-nang-vichy-bao-ve-da-ngan-ngua-lao-hoa-spf50-50ml_1.jpg', 'Kem Chống Nắng Vichy Bảo Vệ Da, Ngăn Ngừa Lão Hóa Ideal Soleil Anti-Aging SPF50 UVA + UVB 50ml đến từ thương hiệu dược mỹ phẩm Vichy của Pháp, là sản phẩm chống nắng mang lại tác động chống lão hóa 3 trong 1, giúp bảo vệ làn da của bạn trước tác động gây lão hóa của ánh nắng mặt trời, đồng thời nuôi dưỡng cho làn da khỏe mạnh và tươi trẻ, cải thiện kết cấu da', 'Chiết xuất từ trái Camu Camu: loại “thần dược” có đến 60 lần lượng Vitamin C chứa trong quả cam, có khả năng chống oxy hóa mạnh mẽ, kích thích sản sinh Collagen, mang lại làn da săn chắc và tươi trẻ hơn, xóa mờ các nếp nhăn li ti, làm sáng và đều màu da.\r\nChiết xuất trà đen Kombucha: thành phần kết hợp giữa AHA, Vitamin & Polyphenos có khả năng chống oxy hóa gấp 100 lần so với Vitamin C, vừa giúp ngăn ngừa các dấu hiện lão hóa da, vừa cải thiện kết cấu làn da.\r\nVitamin E: chống oxy hóa, dưỡng da ẩm mượt mịn màng.\r\nNước khoáng Vichy: với 15 loại khoáng chất giúp tăng cường sức khỏe cho làn da chống lại những tác nhân gây hại từ môi trường, cấp ẩm và làm dịu mát da tức thì.\r\nThành phần đầy đủ:\r\n\r\nAqua/Water, Homosalate, Silica, Ethylhexyl Salicylate, Ethylhexyl Triazone, Glycerin, C12-15 Alkyl Benzoate, Bis-Ethylhexyloxyphenol Methoxyphenyl Triazine, Drometrizole Trisiloxane, Butyl Methoxydibenzoylmethane, Saccharomyces/ Xylinum/ Black Tea Ferment, Aluminym Starch Octenylsuccinate, Octoc', '- Làm sạch tay và rửa mặt với nước tẩy trang và sữa rửa mặt.\r\n\r\n- Thoa kem chống nắng ở công đoạn cuối cùng.\r\n\r\n- Lấy một lượng sản phẩm vửa đủ ra lòng bàn tay.\r\n\r\n- Dùng tay đã thoa kem chống nắng vỗ nhẹ lên bề mặt da.\r\n\r\n- Nên thoa kem 15-20 phút trước khi chuẩn bị ra ngoài để kem có thể ngấm sâu vào da và phát huy tác dụng.\r\n\r\n- Thoa lại sau mỗi 2h khi chơi thể thao, bơi lội, hoạt động mạnh gây tiết nhiều mồ hôi.\r\n\r\n- Tẩy trang và rửa mặt thật sạch vào cuối ngày.'),
(13, 2, 'Himalaya Herbals', 'Son Dưỡng Môi Himalaya Herbals 10g', 'Lip balm', 64000, 75000, 11000, 'https://media.hasaki.vn/catalog/product/s/o/son-duong-moi-himalaya-herbals-10g_1_img_300x300_b798dd_fit_center.jpg', 'https://media.hasaki.vn/wysiwyg/UYEN/son-duong-moi-himalaya-herbals_3_.jpg', 'Son Dưỡng Môi Himalaya Herbals với thành phần từ bơ cao cấp, giàu vitamin E giúp cung cấp dưỡng chất, dưỡng ẩm sâu giữ cho môi luôn căng mịn, khỏe mạnh, phòng ngừa nứt nẻ do thời tiết hanh khô đồng thời có thể được sử dụng như một lớp lót trước khi tô son màu để chống khô và bảo vệ môi', 'Nội dung đang được cập nhật', '- Thoa lên môi bất cứ lúc nào bạn cảm thấy môi cần được cấp ẩm.\r\n\r\n- Dùng trước khi tô son màu để chống khô và bảo vệ môi \r\n\r\n- Có thể thoa son trước khi đi ngủ, sáng hôm sau môi bạn sẽ hồng hào, căng mịn thấy rõ'),
(14, 2, 'Himalaya Herbals', 'Son Dưỡng Môi Himalaya Herbals Hương Dâu 4.5g', 'Strawberry Shine Lip Care', 70000, 85000, 15000, 'https://media.hasaki.vn/catalog/product/s/o/son-duong-moi-himalaya-herbals-huong-dau-4-5g_img_300x300_b798dd_fit_center.jpg', 'https://media.hasaki.vn/wysiwyg/UYEN/son-duong-moi-himalaya-herbals_6_.jpg', 'Son Dưỡng Môi Himalaya Herbals với thành phần từ bơ cao cấp, giàu vitamin E giúp cung cấp dưỡng chất, dưỡng ẩm sâu giữ cho môi luôn căng mịn, khỏe mạnh, phòng ngừa nứt nẻ do thời tiết hanh khô đồng thời có thể được sử dụng như một lớp lót trước khi tô son màu để chống khô và bảo vệ môi.', 'Nội dung đang được cập nhật', '- Thoa lên môi bất cứ lúc nào bạn cảm thấy môi cần được cấp ẩm.\r\n\r\n- Dùng trước khi tô son màu để chống khô và bảo vệ môi \r\n\r\n- Có thể thoa son trước khi đi ngủ, sáng hôm sau môi bạn sẽ hồng hào, căng mịn thấy rõ'),
(15, 2, 'CLINIQUE', 'Son Dưỡng Môi Clinique 4g (HSD 09/2022)', 'Repairwear Intensive Lip Treatment (Date 09/2022)', 329000, 920000, 591000, 'https://media.hasaki.vn/catalog/product/s/o/son-duong-moi-clinique-4g_img_300x300_b798dd_fit_center.jpg', 'https://media.hasaki.vn/wysiwyg/quynhtrang/Trang/son-duong-moi-clinique-4g2.jpg', 'Để đôi môi luôn căng mượt, ẩm mọng trong mọi điều kiện thời tiết thì son dưỡng môi là món đồ không thể thiếu của mọi cô gái. Thị trường son dưỡng khá đa dạng với hàng nghìn sự lựa chọn, tuy nhiên để tìm được một thỏi son dưỡng với bảng thành phần lành tính và công dụng tốt lại không phải một điều dễ dàng. Tại Hasaki, Clinique Repairwear Intensive Lip Treatment là cây son dưỡng môi giàu dưỡng chất giúp tạo đường nét môi, mang lại vẻ căng mọng cho đôi môi, đồng thời giúp làn môi thêm mượt mềm, quyến rũ. Hơn nữa, bạn có thể sử dụng sản phẩm này như lớp nền môi giúp son môi lên màu chuẩn, tươi sáng và sắc nét hơn.\r\n\r\n', 'Octyldodecanol, Pentaerythrityl Adipate/Caprate/Caprylate/Heptanoate, Petrolatum, Bis-Diglyceryl Polyacyladipate-2, Polyethylene, Hydrogenated Dilinoleyl Alcohol, Stearoxy Dimethicone, Silica, Polybutene, Microcrystalline Wax\\Cera Microcristallina\\Cire Microcristalline, Water\\Aqua\\Eau, Triticum Vulgare (Wheat) Germ Extract, Polygonum Cuspidatum Root Extract, Theobroma Grandiflorum Seed Butter, Coffea Arabica (Coffee) Seed Extract, Rosmarinus Officinalis (Rosemary) Leaf Extract, Tocopheryl Acetate, Coffea Robusta Seed Extract, Betula Alba (Birch) Extract, Astrocaryum Murumuru Seed Butter, Hordeum Vulgare (Barley) Extract\\Extrait D\'orge, Butyrospermum Parkii (Shea Butter), Glycerin, Poria Cocos Sclerotium Extract, Linolenic Acid, Sodium DNA, Saccharomyces Lysate Extract, Linoleic Acid, Cholesterol, Sodium RNA, Ascorbyl Tocopheryl Maleate, Methyl Glucose Sesquistearate, Lauryl PCA, C20-40 Pareth-10, Squalane, Ethylhexylglycerin, Polyglyceryl-4 Isostearate, Hexyl Laurate, Cetyl PEG/PPG-10/', 'Thoa trực tiếp lên môi.'),
(16, 2, 'MEDIHEAL', 'Son Dưỡng Mediheal Làm Mềm Vết Thâm & Mềm Môi 10ml', 'Labocare Pan + Eno Lips Healbalm', 68000, 143000, 75000, 'https://media.hasaki.vn/catalog/product/s/o/son-duong-dac-tri-tham-va-lam-mem-moi-10ml_img_300x300_b798dd_fit_center.jpg', 'https://media.hasaki.vn/wysiwyg/tho/Contents_3.jpg', 'Có nhiều nguyên nhân làm đôi môi chúng ta xỉn màu, thâm sạm và nứt nẻ khó chịu, vì vậy việc chăm sóc đôi môi khô nứt trở thành vấn đề khó giải quyết của nhiều chị em phụ nữ. Vậy nên Hasaki.vn xin giới thiệu đến các bạn tuýp son dưỡng làm giảm thâm và làm mềm môi Labocare Pan + Eno Lips Healbalm đến từ Mediheal giúp chăm sóc toàn diện cho đôi môi bạn trở nên hồng hào, mềm mại và căng bóng như cánh hoa hồng mới nở.', 'Nội dung đang được cập nhật', '- Tẩy tế bào chết cho môi\r\n\r\n- Lấy 1 lượng chất kem cỡ hạt đậu nhỏ rồi thoa đều khắp môi và đi ngủ. '),
(17, 2, 'HURRAW!', 'Son Dưỡng Môi HURRAW! Hương Chuối 4.8g', 'Baobab Banana Lip Balm', 105000, 145000, 40000, 'https://media.hasaki.vn/catalog/product/s/o/son-duong-moi-hurraw-huong-chuoi-4-8g_img_300x300_b798dd_fit_center.jpg', 'https://media.hasaki.vn/wysiwyg/HaNguyen/son-duong-moi-hurraw-4-8g-cherry-1.jpg', 'Da môi của chúng ta là vùng da rất mỏng manh nhạy cảm, lại không có tuyến mồ hôi như da mặt nên cực kì dễ bị mất độ ẩm, gây ra tình trạng môi khô nẻ, bong tróc khó chịu. Nếu không được bảo vệ và cung cấp độ ẩm, tình trạng khô môi lại càng tồi tệ hơn. Vì thế, bí quyết để sở hữu đôi môi căng mọng, mịn màng và hồng hào tự nhiên chính là thường xuyên sử dụng son dưỡng môi hằng ngày đấy. Các nàng đừng quên sở hữu cho mình một thỏi son dưỡng môi xinh xắn và mang theo trong túi xách để thoa mỗi khi cần nhé.\r\n\r\nHasaki xin giới thiệu bộ sưu tập Son Dưỡng Môi HURRAW! Lip Balm nổi tiếng tại Mỹ, với thành phần được chiết xuất hoàn toàn từ tự nhiên được rất nhiều các cô nàng yêu thích. Son Dưỡng Môi HURRAW! sẽ nuôi dưỡng cho bờ môi của các nàng trở nên căng mịn và tươi tắn như một cánh hoa anh đào, thu hút ánh nhìn của người đối diện. Đặc biệt hơn, sản phẩm không chứa các chất có khả năng gây hại cho da môi như iron oxides, carmine, petroleum. Thành phần thuần chay, không chứa các chiết xuất từ ong, bơ Shea, đậu nành, dầu cọ, thân thiện với môi trường và người ăn chay.\r\n\r\nHiện tại Hasaki đang có những phân loại sau:\r\n\r\nBlack Cherry Tinted Lip Balm – Hương Cherry (Có màu)', 'Black Cherry Tinted Lip Balm\r\n\r\nCarthamus tinctorius (safflower) seed oil*, Euphorbia cerifera cera (candelilla) wax, Cocos nucifera (coconut) oil*, Ricinus communis (castor) seed oil*, Theobroma cacao (cacao) seed butter*, Simmondsia chinensis (jojoba) seed oil*, Olea europaea (olive) fruit oil*, Aroma, Tocopherol, Alkanna tinctoria (alkanet) root extract, Helianthus annuus (sunflower) seed oil\r\n\r\nEchium Raspberry Tinted Lip Balm\r\n\r\nCarthamus tinctorius (safflower) seed oil*, Euphorbia cerifera cera (candelilla) wax, Echium plantagineum (echium) seed oil, Cocos nucifera (coconut) oil*, Ricinus communis (castor) seed oil*, Theobroma cacao (cacao) seed butter*, Simmondsia chinensis (jojoba) seed oil*, Olea europaea (olive) fruit oil*, Maltodextrin, Aroma, Tocopherol, Daucus carota sativa (carrot) root extract, Helianthus annuus (sunflower) seed oil, Citric acid\r\n\r\nBaobab Banana Lip Balm\r\n\r\nCarthamus tinctorius (safflower) seed oil*, Euphorbia cerifera cera (candelilla) wax, Adansonia di', 'Thoa lên môi nhiều lần trong ngày, mỗi khi thấy môi bị khô hoặc khi cần.'),
(18, 2, 'VASELINE', 'Son Dưỡng Môi Mềm Mịn Vaseline 4.8g', 'Lip Therapy Original Stick', 47000, 70000, 23000, 'https://media.hasaki.vn/catalog/product/s/o/son-duong-moi-mem-min-vaseline-4-8g_img_300x300_b798dd_fit_center.jpg', 'https://media.hasaki.vn/wysiwyg/quynhtrang/Trang/son-duong-moi-vaseline-dang-thoi-4-8g3.jpg', 'Đôi môi khô của bạn sẽ mềm mịn hẳn nếu sử dụng Vaseline thường xuyên. Với công dụng cung cấp chất dinh dưỡng, mang lại cho bạn làn da mềm mại - Son Dưỡng Môi Dạng Thỏi Vaseline Lip Therapy 4.8g có chức năng vừa là son dưỡng môi, giảm nứt nẻ vừa có thể sử dụng như son lót trang điểm, giúp bảo vệ môi và giúp son lên màu chuẩn hơn. \r\n\r\nVaseline là thương hiệu ra đời từ năm 1870. Thương hiệu này được biết đến lần đầu với sản phẩm sáp Vaseline do Robert Chesebrough tìm ra sau khi ông ghé thăm một mỏ dầu. Từ đó thương hiệu này đã làm một cuộc cách mạng và được sử dụng khắp mọi nơi trên toàn thế giới. Hiện nay, thương hiệu này đang được quản lý bởi tập đoàn Unilever. Các sản phẩm chăm sóc da của thương hiệu Vaseline đã có mặt ở 60 nước trên toàn thế giới và được bày bán ở hệ thống các siêu thị trên cả nước và được các chị em phụ nữ tin tưởng và sử dụng hàng ngày.', '-Chiết xuất hoa hồng\r\nChống ôxy hóa mạnh mẽ, chống viêm lỗ chân lông, làm giảm vết thâm, mụn, mang đến làn da mềm mại, mịn màng\r\n-Chiết xuất lô hội\r\nLàm giảm mụn, làm dịu da, giảm sưng tấy, dưỡng ẩm, làm se lỗ chân lông và ngăn ngừa các dấu hiệu lão hóa.\r\n-Chiết xuất cacao\r\nChống oxi hóa, cải thiện lưu thông máu giúp da hồng hào hơn, tăng sự đàn hồi và độ ẩm cho da\r\n', 'Khi môi các bạn bi khô nên sử dụng thường xuyên ngày và đêm đều được.\r\n\r\nDùng son dưỡng trước sau đó tô son môi vào để có một đôi môi mềm và giúp son lên chuẩn màu hơn.'),
(19, 2, 'HURRAW!', 'Son Dưỡng Môi HURRAW! Hương Chocolate 4.8g', 'Chocolate Lip balm', 101000, 145000, 44000, 'https://media.hasaki.vn/catalog/product/s/o/son-duong-moi-hurraw-huong-chocolate-4-8g_img_300x300_b798dd_fit_center.jpg', 'https://media.hasaki.vn/wysiwyg/HaNguyen/son-duong-moi-hurraw-4-8g-cherry-1.jpg', 'Da môi của chúng ta là vùng da rất mỏng manh nhạy cảm, lại không có tuyến mồ hôi như da mặt nên cực kì dễ bị mất độ ẩm, gây ra tình trạng môi khô nẻ, bong tróc khó chịu. Nếu không được bảo vệ và cung cấp độ ẩm, tình trạng khô môi lại càng tồi tệ hơn. Vì thế, bí quyết để sở hữu đôi môi căng mọng, mịn màng và hồng hào tự nhiên chính là thường xuyên sử dụng son dưỡng môi hằng ngày đấy. Các nàng đừng quên sở hữu cho mình một thỏi son dưỡng môi xinh xắn và mang theo trong túi xách để thoa mỗi khi cần nhé.\r\n\r\nHasaki xin giới thiệu bộ sưu tập Son Dưỡng Môi HURRAW! Lip Balm nổi tiếng tại Mỹ, với thành phần được chiết xuất hoàn toàn từ tự nhiên được rất nhiều các cô nàng yêu thích. Son Dưỡng Môi HURRAW! sẽ nuôi dưỡng cho bờ môi của các nàng trở nên căng mịn và tươi tắn như một cánh hoa anh đào, thu hút ánh nhìn của người đối diện. Đặc biệt hơn, sản phẩm không chứa các chất có khả năng gây hại cho da môi như iron oxides, carmine, petroleum. Thành phần thuần chay, không chứa các chiết xuất từ ong, bơ Shea, đậu nành, dầu cọ, thân thiện với môi trường và người ăn chay.\r\n\r\nHiện tại Hasaki đang có những phân loại sau:\r\n\r\nBlack Cherry Tinted Lip Balm – Hương Cherry (Có màu)', 'Black Cherry Tinted Lip Balm\r\n\r\nCarthamus tinctorius (safflower) seed oil*, Euphorbia cerifera cera (candelilla) wax, Cocos nucifera (coconut) oil*, Ricinus communis (castor) seed oil*, Theobroma cacao (cacao) seed butter*, Simmondsia chinensis (jojoba) seed oil*, Olea europaea (olive) fruit oil*, Aroma, Tocopherol, Alkanna tinctoria (alkanet) root extract, Helianthus annuus (sunflower) seed oil\r\n\r\nEchium Raspberry Tinted Lip Balm\r\n\r\nCarthamus tinctorius (safflower) seed oil*, Euphorbia cerifera cera (candelilla) wax, Echium plantagineum (echium) seed oil, Cocos nucifera (coconut) oil*, Ricinus communis (castor) seed oil*, Theobroma cacao (cacao) seed butter*, Simmondsia chinensis (jojoba) seed oil*, Olea europaea (olive) fruit oil*, Maltodextrin, Aroma, Tocopherol, Daucus carota sativa (carrot) root extract, Helianthus annuus (sunflower) seed oil, Citric acid\r\n\r\nBaobab Banana Lip Balm\r\n\r\nCarthamus tinctorius (safflower) seed oil*, Euphorbia cerifera cera (candelilla) wax, Adansonia di', 'Thoa lên môi nhiều lần trong ngày, mỗi khi thấy môi bị khô hoặc khi cần.'),
(20, 2, 'HURRAW!', 'Son Dưỡng Môi HURRAW! Hương Vani 4.8g', 'Vanilla Bean Lip Balm', 105000, 145000, 40000, 'https://media.hasaki.vn/catalog/product/s/o/son-duong-moi-hurraw-huong-vani-4-8g_img_300x300_b798dd_fit_center.jpg', 'https://media.hasaki.vn/wysiwyg/HaNguyen/son-duong-moi-hurraw-4-8g-cherry-1.jpg', 'Da môi của chúng ta là vùng da rất mỏng manh nhạy cảm, lại không có tuyến mồ hôi như da mặt nên cực kì dễ bị mất độ ẩm, gây ra tình trạng môi khô nẻ, bong tróc khó chịu. Nếu không được bảo vệ và cung cấp độ ẩm, tình trạng khô môi lại càng tồi tệ hơn. Vì thế, bí quyết để sở hữu đôi môi căng mọng, mịn màng và hồng hào tự nhiên chính là thường xuyên sử dụng son dưỡng môi hằng ngày đấy. Các nàng đừng quên sở hữu cho mình một thỏi son dưỡng môi xinh xắn và mang theo trong túi xách để thoa mỗi khi cần nhé.\r\n\r\nHasaki xin giới thiệu bộ sưu tập Son Dưỡng Môi HURRAW! Lip Balm nổi tiếng tại Mỹ, với thành phần được chiết xuất hoàn toàn từ tự nhiên được rất nhiều các cô nàng yêu thích. Son Dưỡng Môi HURRAW! sẽ nuôi dưỡng cho bờ môi của các nàng trở nên căng mịn và tươi tắn như một cánh hoa anh đào, thu hút ánh nhìn của người đối diện. Đặc biệt hơn, sản phẩm không chứa các chất có khả năng gây hại cho da môi như iron oxides, carmine, petroleum. Thành phần thuần chay, không chứa các chiết xuất từ ong, bơ Shea, đậu nành, dầu cọ, thân thiện với môi trường và người ăn chay.\r\n\r\nHiện tại Hasaki đang có những phân loại sau:\r\n\r\nBlack Cherry Tinted Lip Balm – Hương Cherry (Có màu)', 'Black Cherry Tinted Lip Balm\r\n\r\nCarthamus tinctorius (safflower) seed oil*, Euphorbia cerifera cera (candelilla) wax, Cocos nucifera (coconut) oil*, Ricinus communis (castor) seed oil*, Theobroma cacao (cacao) seed butter*, Simmondsia chinensis (jojoba) seed oil*, Olea europaea (olive) fruit oil*, Aroma, Tocopherol, Alkanna tinctoria (alkanet) root extract, Helianthus annuus (sunflower) seed oil\r\n\r\nEchium Raspberry Tinted Lip Balm\r\n\r\nCarthamus tinctorius (safflower) seed oil*, Euphorbia cerifera cera (candelilla) wax, Echium plantagineum (echium) seed oil, Cocos nucifera (coconut) oil*, Ricinus communis (castor) seed oil*, Theobroma cacao (cacao) seed butter*, Simmondsia chinensis (jojoba) seed oil*, Olea europaea (olive) fruit oil*, Maltodextrin, Aroma, Tocopherol, Daucus carota sativa (carrot) root extract, Helianthus annuus (sunflower) seed oil, Citric acid\r\n\r\nBaobab Banana Lip Balm\r\n\r\nCarthamus tinctorius (safflower) seed oil*, Euphorbia cerifera cera (candelilla) wax, Adansonia di', 'Thoa lên môi nhiều lần trong ngày, mỗi khi thấy môi bị khô hoặc khi cần.'),
(21, 2, 'VASELINE', 'Son Dưỡng Môi Vaseline Hồng Xinh 4.8g', 'Lip Therapy Rosy Lips Stick', 49000, 70000, 21000, 'https://media.hasaki.vn/catalog/product/s/o/son-duong-moi-hong-xinh-vaseline-4-8g_img_300x300_b798dd_fit_center.jpg', 'https://media.hasaki.vn/wysiwyg/quynhtrang/Trang/son-duong-moi-vaseline-dang-thoi-4-8g3.jpg', 'Đôi môi khô của bạn sẽ mềm mịn hẳn nếu sử dụng Vaseline thường xuyên. Với công dụng cung cấp chất dinh dưỡng, mang lại cho bạn làn da mềm mại - Son Dưỡng Môi Dạng Thỏi Vaseline Lip Therapy 4.8g có chức năng vừa là son dưỡng môi, giảm nứt nẻ vừa có thể sử dụng như son lót trang điểm, giúp bảo vệ môi và giúp son lên màu chuẩn hơn. \r\n\r\nVaseline là thương hiệu ra đời từ năm 1870. Thương hiệu này được biết đến lần đầu với sản phẩm sáp Vaseline do Robert Chesebrough tìm ra sau khi ông ghé thăm một mỏ dầu. Từ đó thương hiệu này đã làm một cuộc cách mạng và được sử dụng khắp mọi nơi trên toàn thế giới. Hiện nay, thương hiệu này đang được quản lý bởi tập đoàn Unilever. Các sản phẩm chăm sóc da của thương hiệu Vaseline đã có mặt ở 60 nước trên toàn thế giới và được bày bán ở hệ thống các siêu thị trên cả nước và được các chị em phụ nữ tin tưởng và sử dụng hàng ngày.', '-Chiết xuất hoa hồng\r\nChống ôxy hóa mạnh mẽ, chống viêm lỗ chân lông, làm giảm vết thâm, mụn, mang đến làn da mềm mại, mịn màng\r\n-Chiết xuất lô hội\r\nLàm giảm mụn, làm dịu da, giảm sưng tấy, dưỡng ẩm, làm se lỗ chân lông và ngăn ngừa các dấu hiệu lão hóa.\r\n-Chiết xuất cacao\r\nChống oxi hóa, cải thiện lưu thông máu giúp da hồng hào hơn, tăng sự đàn hồi và độ ẩm cho da', 'Khi môi các bạn bi khô nên sử dụng thường xuyên ngày và đêm đều được.\r\n\r\nDùng son dưỡng trước sau đó tô son môi vào để có một đôi môi mềm và giúp son lên chuẩn màu hơn.'),
(22, 2, 'NIVEA', 'Son Dưỡng Môi Nivea Chuyên Sâu 4.8g', 'Original Care Caring Lip Balm', 51000, 66000, 15000, 'https://media.hasaki.vn/catalog/product/s/o/son-duong-moi-nivea-chuyen-sau-4-8g-1_img_300x300_b798dd_fit_center.jpg', 'https://media.hasaki.vn/wysiwyg/HaNguyen/son-duong-moi-nivea-4-8g-1.jpg', 'Son Dưỡng Môi Nivea Caring Lip Balm là dòng sản phẩm chăm sóc da môi đến từ thương hiệu mỹ phẩm Nivea danh tiếng xuất xứ từ Đức, có công thức không chứa chì an toàn cho làn da môi nhạy cảm, giúp cung cấp độ ẩm chuyên sâu giúp da môi luôn mềm mượt và mịn màng. Dòng sản phẩm hiện có các phân loại như sau:\r\n\r\n-Original - Hương Nguyên Bản (Không Màu)\r\n\r\n-Strawberry - Hương Dâu Dịu Ngọt (Màu Đỏ)\r\n\r\n-Peach - Hương Đào Ngọt Ngào (Màu Cam)\r\n\r\n-Cherry - Hương Anh Đào Quyến Rũ (Màu Hồng Tím)', 'Nivea Original Care Caring Lip Balm\r\n\r\nCera Microcristallina, Octyldodecanol, Hydrogenated Polydecene, Cetyl Palmitate, Ricinus Communis Seed Oil, Myristyl Myristate, VP/Hexadecene Copolymer, Cetearyl Alcohol, Polyglyceryl-3 Diisostearate, Butyrospermum Parkii Butter, Caprylic/Capric Triglyceride, Pentaerythrityl Tetraisostearate, VP/Eicosene Copolymer, C20-40 Alkyl Stearate, Panthenol, Copernicia Cerifera Cera, Cera Alba, Aqua, Glycerin, Parfum\r\n\r\nNivea Strawberry Shine Lip Balm\r\n\r\nRicinus Communis Seed Oil, Polyisobutene, Octyldodecanol, Pentaerythrityl Tetraisostearate, Hydrogenated Polydecene, Candelilla Cera, Butyrospermum Parkii Butter, Cera Microcristallina, Isopropyl Palmitate, Synthetic Wax, Polyglyceryl-3 Diisostearate, Glycerin, Glyceryl Glucoside, Aqua, Fragaria Ananassa Fruit Juice, Mica, Propylene Glycol, BHT, Aroma, CI 15985, CI 77891, CI 15850\r\n\r\nNivea Peach Shine Lip Balm\r\n\r\nOctyldodecanol, Polyisobutene, Ricinus Communis Seed Oil, Pentaerythrityl Tetraisostearate, Hyd', '-Bôi son dưỡng lên môi bất kỳ khi nào trong ngày hay những lúc cảm thấy môi bị khô, bong tróc, thiếu sức sống. \r\n\r\n-Có thể thoa son dưỡng trước khi ngủ giúp cho đôi môi luôn mềm mịn và không bị mất nước.'),
(23, 2, ' Pretty by Flormar', 'Son Dưỡng Pretty By Flormar 001 Cherry 4.8g', 'Lip Balm', 74000, 99000, 25000, 'https://media.hasaki.vn/catalog/product/s/o/son-duong-pretty-by-flormar-001-4-8g_img_300x300_b798dd_fit_center.jpg', 'https://media.hasaki.vn/wysiwyg/AnhThu/Son-Duong-Pretty-By-Flormar-Lip-Balm-4-8g.jpg', 'Son Dưỡng Pretty By Flormar Lip Balm 4.8g là dòng son dưỡng đến từ thương hiệu mỹ phẩm trang điểm Flormar nổi tiếng của Ý sẽ mang đến cho bạn đôi môi tươi tắn và mềm mịn suốt cả ngày dài. Thời tiết hanh khô hay thường xuyên sinh hoạt trong môi trường máy lạnh khiến đôi môi bạn bị khô và nứt nẻ? Hiểu được điều này, son dưỡng Pretty By Flormar Lip Balm 4.8g sẽ bổ sung và cân bằng độ ẩm cho đôi môi của bạn luôn mềm mượt mịn màng; đồng thời bảo vệ môi tối đa trước tác hại của ánh nắng mặt trời, giữ sắc hồng nhẹ tươi tắn cho đôi môi.', 'Nội dung đang được cập nhật', 'Khi môi các bạn bi khô nên sử dụng thường xuyên ngày và đêm đều được.\r\n\r\nDùng son dưỡng trước sau đó tô son môi vào để có một đôi môi quyến rũ, sexy như ý.'),
(24, 2, 'Himalaya Herbals', 'Son Dưỡng Môi Himalaya Herbals Hương Bơ Cacao 4.5g', 'Intensive Moisturizing Cocoa Butter Lip Balm', 70000, 85000, 15000, 'https://media.hasaki.vn/catalog/product/s/o/son-duong-moi-himalaya-herbals-huong-bo-cacao-4-5g_img_300x300_b798dd_fit_center.jpg', 'https://media.hasaki.vn/wysiwyg/UYEN/son-duong-moi-himalaya-herbals_6_.jpg', 'Son Dưỡng Môi Himalaya Herbals với thành phần từ bơ cao cấp, giàu vitamin E giúp cung cấp dưỡng chất, dưỡng ẩm sâu giữ cho môi luôn căng mịn, khỏe mạnh, phòng ngừa nứt nẻ do thời tiết hanh khô đồng thời có thể được sử dụng như một lớp lót trước khi tô son màu để chống khô và bảo vệ môi.\r\n\r\n', 'Nội dung đang được cập nhật', ' Thoa lên môi bất cứ lúc nào bạn cảm thấy môi cần được cấp ẩm.\r\n\r\n- Dùng trước khi tô son màu để chống khô và bảo vệ môi \r\n\r\n- Có thể thoa son trước khi đi ngủ, sáng hôm sau môi bạn sẽ hồng hào, căng mịn thấy rõ');

--
-- Chỉ mục cho các bảng đã đổ
--

--
-- Chỉ mục cho bảng `db_content`
--
ALTER TABLE `db_content`
  ADD PRIMARY KEY (`id`),
  ADD KEY `fk-cate-content` (`cid`);

--
-- Các ràng buộc cho các bảng đã đổ
--

--
-- Các ràng buộc cho bảng `db_content`
--
ALTER TABLE `db_content`
  ADD CONSTRAINT `fk-cate-content` FOREIGN KEY (`cid`) REFERENCES `db_category` (`id`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
